[workspace]

members = [
    "tetrs_tui",
    "tetrs_engine",
]
resolver = "2"

#[profile.release]
#strip = true  # Automatically strip symbols from the binary.
#opt-level = "z"  # Optimize for size.
#lto = true # Link-time optimization.
